[package]
name = "concurrency"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.87"
dashmap = "6.1.0"
oneshot = "0.1.8"
rand = "0.8.5"
tokio = { version = "1.40.0", features = ["rt", "rt-multi-thread", "macros", "net", "io-util"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
